Telegram bot implementation
bettersg/SchemesSG_v3 pull request #37
Opened 2024-09-22 09:14 UTC by CJBuzz

Implemented telegram bot (that calls backend's API)

2024-09-25 17:50 UTC, rebeccacxy requested changes

2024-09-25 17:50 UTC, rebeccacxy commented on telegram_bot/handlers/main_handlers.py
> +    if mode == "chat":  # If "Let's Chat!" button is pressed
use enum for modes

2024-09-25 17:50 UTC, rebeccacxy commented on telegram_bot/utils/api.py
> +    if len(schemes) == 0:  # No suitable schemes found
```suggestion
    if not schemes:  # No suitable schemes found
```
follow [pep8](https://peps.python.org/pep-0008/)
> Don’t check for empty containers or sequences (like [] or '') by comparing the length to zero (if len(somelist) == 0). Use if not somelist and assume that empty values will implicitly evaluate to False.

2024-09-27 02:01 UTC, CJBuzz commented on telegram_bot/handlers/main_handlers.py
> +    if mode == "chat":  # If "Let's Chat!" button is pressed
I just made the suggested change

2024-09-28 15:18 UTC, rebeccacxy approved these changes

2024-09-28 15:19 UTC, merged